apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pets-rest-api
  name: pets-rest-api
  namespace: default
spec:
  selector:
    matchLabels:
      app: pets-rest-api
  replicas: 1
  template:
    metadata:
      labels:
        app: pets-rest-api
    spec:
      containers:
      - image: kcbabo/pets-rest-api:latest
        name: pets-rest-api
        ports:
        - containerPort: 5000
          name: http