apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: petstore-rt
  namespace: gloo-mesh-gateways
  labels:
     portal: dev-portal
     api: petstore
spec:
  portalMetadata:
    title: Petstore REST API
    description: Totally awesome API for all things pets!
  http:
  - name: pets-api
    labels:
      usagePlans: dev-portal
      cors-policy: api
    matchers:
    - uri:
        prefix: /pet
    forwardTo:
      destinations:
      - ref:
          name: pets-rest-api
          namespace: default
        port:
          number: 5000