apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: store-rest-api
  name: store-rest-api
  namespace: default
spec:
  selector:
    matchLabels:
      app: store-rest-api
  replicas: 1
  template:
    metadata:
      labels:
        app: store-rest-api
    spec:
      containers:
      - image: duncandoyle/store-rest-api:latest
        name: store-rest-api
        ports:
        - containerPort: 5000
          name: http