apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: users-rest-api
  name: users-rest-api
  namespace: default
spec:
  selector:
    matchLabels:
      app: users-rest-api
  replicas: 1
  template:
    metadata:
      labels:
        app: users-rest-api
    spec:
      containers:
      - image: duncandoyle/users-rest-api:latest
        name: users-rest-api
        ports:
        - containerPort: 5000
          name: http